version: '2'

services:
  web: 
    build: ./app
    ports:
      - 8080:80
    depends_on:
      - db
    env_file:
      - env_test
  db: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - env_test
volumes:
  mysql_data: