name: actions 
on: [ push, pull_request]
jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker-compose build
      run: docker-compose build
    - name: docker-compose up
      run: |
          docker-compose up -d
          sleep 10
          docker ps
    - name: grep "Error"
      run: | 
        if curl -s localhost:8080 | grep -q "Error" ; then
          docker logs resolutions-php_web_1
          docker logs resolutions-php_db_1
          exit 1 
        fi
    - name: grep "Failed to connect to MySQL"
      run: | 
        if curl -s localhost:8080 | grep -q "Failed to connect to MySQL" ; then
          docker logs resolutions-php_web_1
          docker logs resolutions-php_db_1
          exit 1 
        fi