name: actions 
on: [ push, pull_request]
jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker-compose build
      run: docker-compose build
    - name: docker-compose up (plus sleep)
      run: |
        docker-compose up -d
        sleep 10
        docker ps
    - name: check web-output looks correct
      run: | 
        curl -s localhost:80 /tmp/output.html
        if cat /tmp/output.html | grep -q "Error" ; then
          echo "Error detected in web-output"
          exit 1 
        fi
        if cat /tmp/output.html | grep -q "Failed to connect to MySQL" ; then
          echo "Failed  MySQL detected in web-output"
          exit 1 
        fi
        if (( $(cat /tmp/output.html | grep -c '</option>') < 100 )); then
          echo "Number of generated option-tags < 100, seems suspiciously low"
          exit 1
        fi
