name: actions 
on: [ push, pull_request]
jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker-compose build
      run: docker-compose build
    - name: docker-compose up
      run: |
          docker-compose up -d
          sleep 10
          docker ps
    - name: empty DB and run init.sql, when DB is empty
      run: |
        source empty_db.sh
        env $(cat env_test | xargs) mysql --user=$WMORESOLUTIONS_USER --password=$WMORESOLUTIONS_PWD --host=localhost $WMORESOLUTIONS_DB < init.sql
    - name: empty DB and run init.sql, when DB not empty
      run: |
        source empty_db.sh
        env $(cat env_test | xargs) mysql --user=$WMORESOLUTIONS_USER --password=$WMORESOLUTIONS_PWD --host=localhost $WMORESOLUTIONS_DB < init.sql
    - name: curl 8080 and check for "Error"
      run: | 
        if curl -s localhost:8080 | grep -q "Error" ; then
          echo "Error detected in web-output"
          docker logs wmo-resolutions-php_web_1
          docker logs wmo-resolutions-php_db_1
          exit 1 
        fi
    - name: curl 8080 and check for "Failed to connect to MySQL"
      run: | 
        if curl -s localhost:8080 | grep -q "Failed to connect to MySQL" ; then
          echo "Failed  MySQL detected in web-output"
          docker logs wmo-resolutions-php_web_1
          docker logs wmo-resolutions-php_db_1
          exit 1 
        fi